library("dplyr")
library("datasets")
data(iris)
summary(iris)
#a)
col1 <- mutate(iris, Proportion = round(Sepal.Length/Sepal.Width, 2))
tail(col1)
#b)
summarised <- summarise(iris, Avg_slength = mean(Sepal.Length))
head(summarised)
#c)
selected <- select(iris, Sepal.Length, Sepal.Width, Petal.Length)
head(selected)